# Numpy

## 1 Array

In [5]:
# Creating array

import numpy as np

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [11]:
c = np.ones(4)
c

array([1., 1., 1., 1.])

In [14]:
d = np.empty(5) #random array generator
d

array([9.34562257e-307, 2.11382017e-307, 1.89142822e-307, 3.11522563e-307,
       9.45708168e-308])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
# Add, Remove, Sort

In [22]:
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [26]:
w = np.append(np.arange(1,5,2),[1,2,3])
w

array([1, 3, 1, 2, 3])

In [27]:
q = np.append(a,c)
q

array([ 0.,  2.,  4.,  6.,  8., 10.,  1.,  1.,  1.,  1.])

In [29]:
r = np.delete(q,6)
r

array([ 0.,  2.,  4.,  6.,  8., 10.,  1.,  1.,  1.])

In [33]:
me = np.delete(r,(1,2))# delete index 1,2
me

array([ 0.,  6.,  8., 10.,  1.,  1.,  1.])

In [32]:
np.sort(r) #sorting urutan dr yg terbesar ke terkecil

array([ 0.,  1.,  1.,  1.,  2.,  4.,  6.,  8., 10.])

In [34]:
# how to add array in array at certain index; 
# how to delete scalar in array at certain index range e.g index 1-3; 
# how to np.sort dari yg terbesar ke terkecil



In [41]:
example = np.array([[[1,2,3],
                     [2,3,4]],
                    [[3,4,5],
                     [4,5,6]],
                    [[5,6,7],
                     [6,7,8]]])
print(example)


[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]

 [[5 6 7]
  [6 7 8]]]


In [43]:
np.ndim(example)

3

In [44]:
np.size(example)

18

In [45]:
np.shape(example) #dimension, row, column

(3, 2, 3)

In [46]:
r


array([ 0.,  2.,  4.,  6.,  8., 10.,  1.,  1.,  1.])

In [48]:
# Reshape

In [49]:
r

array([ 0.,  2.,  4.,  6.,  8., 10.,  1.,  1.,  1.])

In [51]:
g = np.reshape(9,1)
g 

array([9])

In [54]:
h = np.empty(6)
h

array([ 6.,  8., 10.,  1.,  1.,  1.])

In [57]:
y = np.reshape(h, (6,1))
y

array([[ 6.],
       [ 8.],
       [10.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [58]:
np.reshape(h,(3,2))

array([[ 6.,  8.],
       [10.,  1.],
       [ 1.,  1.]])

In [60]:
# Convert 1D to 2D

In [62]:
a = np.empty(4)
a

array([1., 1., 1., 1.])

In [66]:
b = np.array([1,2,3])

In [70]:
c = b[np.newaxis]
c

array([[1, 2, 3]])

In [71]:
np.shape(c)

(1, 3)

In [68]:
a[np.newaxis]

array([[[[1., 1., 1., 1.]]]])

In [72]:
b


array([1, 2, 3])

In [73]:
np.expand_dims(b,axis=0) # jadinya (1,3)

array([[1, 2, 3]])

In [74]:
np.expand_dims(b,axis=1) # jadinya (3,1)

array([[1],
       [2],
       [3]])

In [75]:
# Indexing and Slicing

In [78]:
random = np.empty(4)
print(random)
random[2]

[1. 1. 1. 1.]


1.0

In [79]:
example

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]],

       [[5, 6, 7],
        [6, 7, 8]]])

In [80]:
example[17:]

array([], shape=(0, 2, 3), dtype=int32)

In [82]:
example[example>=17]

array([], dtype=int32)

In [83]:
# PR SLICING IN ARRAY

In [84]:
# Create an array from existing data

In [95]:
a = np.array([[1,2,3],
              [2,3,4],
              [3,4,5]])
            
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [96]:
np.shape(a)

(3, 3)

In [97]:
##

m_1 = np.array([[1,2],[3,4]])
m_2 = np.array([[5,6],[7,8]])

print(m_1)
print(m_2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [99]:
np.vstack((m_1,m_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
# Basic Array Operation

In [101]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [102]:
c = a[1]
c

array([2, 3, 4])

In [103]:
d = a[0]
d

array([1, 2, 3])

In [104]:
c + d


array([3, 5, 7])

In [105]:
d.sum()

6

In [106]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [107]:
a.sum(axis=0)# sum menurun

array([ 6,  9, 12])

In [108]:
a.sum(axis=1)#sum mendatar

array([ 6,  9, 12])

## 2 MATRICES

In [110]:
random = np.random.random((3,3))#completely random
random

array([[0.11688521, 0.04432774, 0.46760294],
       [0.56934506, 0.62101956, 0.82942501],
       [0.31768405, 0.51789009, 0.25110553]])

In [111]:
matrix1 = np.array([[1,3,5],[4,5,6]])
matrix1

array([[1, 3, 5],
       [4, 5, 6]])

In [113]:
np.ndim(matrix1)

2

In [114]:
np.shape(matrix1)

(2, 3)

In [124]:
random1 = np.random.random((1,2))
random2 = np.random.random((2,1))

In [125]:
print(random1)
print(random2)

[[0.10802853 0.76751714]]
[[0.45832287]
 [0.62818015]]


In [126]:
np.dot(random1,random2)

array([[0.53165098]])

In [127]:
random1[0,0]

0.10802852961613774

In [133]:
random3 = np.random.random((4,4))
random3

array([[0.05629205, 0.96294506, 0.96874216, 0.08849841],
       [0.81617151, 0.06877747, 0.22788359, 0.5856189 ],
       [0.07431731, 0.54201258, 0.68094156, 0.66333092],
       [0.41591597, 0.9215933 , 0.5010074 , 0.74766012]])

In [134]:
random3[0:6,1]

array([0.96294506, 0.06877747, 0.54201258, 0.9215933 ])